name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # uruchamia workflow przy push/merge do main

permissions:
  contents: write   # pozwala GH Actions pushować na dowolny branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Cache npm dependencies
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('FocusApp/package-lock.json') }}

      # 4. Install npm dependencies
      - name: Install npm dependencies
        working-directory: FocusApp
        run: npm ci

      # 5. Build Angular app
      - name: Build Angular app
        working-directory: FocusApp
        run: npx ng build --configuration production --base-href "/Focus/"

      # 6. Copy index data to 404 to enables routing
      - name: Copy index.html to 404.html
        working-directory: FocusApp/dist/FocusApp/browser
        run: cp index.html 404.html

      # 7. Show build output for debugging
      - name: List build output
        working-directory: FocusApp
        run: ls -R dist

      # 8. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: FocusApp/dist/FocusApp/browser
          publish_branch: gh-pages
